### ISSUE TITLE
Tests for fetch subpackage arent reusable and maintainable

### ISSUE THREAD

**Issue by sekgobela-kevin** [Sekgobela-Kevin/naval#2]
Tests classes needs to atleat inherit from common test class that will define common test methods.
This will make changing  and updating tests much more easy.

**Comment by Sekgobela-Kevin** [comment]
The latest commit(1e4c55a3) attempted to make them reusable.
Its just one step to making the tests better.

**Comment by sekgobela-kevin** [comment]
Commit(https://github.com/Sekgobela-Kevin/naval/commit/1e4c55a3d08340c97b980943bc5f33047f216115) is enough to resolve the issue. So I am going to close the issue as its no longer a case, if tests for fetch subpackage arent reusable then all tests for project arent usable.

**Comment by sekgobela-kevin** [comment]
First release has been released and its also available on [pypi](https://pypi.org/project/navaly/).
